services:
  zkguard-bench:
    image: ${IMAGE:-zkguard}:${TAG:-bench}
    build:
      context: ${SOURCE_ROOT?err_unset}
      dockerfile: ./docker/dockerfiles/zkguard.Dockerfile
      args:
        - PROFILE=production
        - FEATURES=runtime-benchmarks
    entrypoint: [ "" ]
    command: [ "/bin/bash" ]
    container_name: zkverify-bench
    user: "${USER_ID:-0}:${GROUP_ID:-0}"
    volumes:
      - "${SOURCE_ROOT?err_unset}:/data/benchmark:rw"
